name: "Build exec"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install requirements
              run: |
                pip install -r devRequirements.txt
                pip install -r requirements.txt
            - name: Build
              run: pyinstaller --onefile __main__.py
            - name: Rename
              run: mv dist/__main__ release_osx
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release_osx
                  path: release_osx
    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v2
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: release_osx
                  path: release_osx
            - name: Release
              uses: softprops/action-gh-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: "release_osx"
                  tag_name: ${{ github.event.inputs.version }}
                  name: ${{ github.event.inputs.version }}
                  